spring:
  datasource:
    url: jdbc:mysql://localhost:3306/memorybook?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate